### PR TITLE
Added cloud functions to the readme

### PR DESCRIPTION
**Pull request by igor9silva**
There is no documentation pointing to the required Cloud Functions at all.

Developers trying to run mobile examples only (android and/or iOS) won't be able to make it work as expected.

Also, even on the web example, there is no instruction regarding publishing the functions.

This PR adds a link to the Cloud Functions into the README.

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
Actually The Android and iOS apps also need to deploy the storage and database auth rules. (that's actually more important than the functions :) ) they'll need some special instructions just to deploy these. Let me add this to the web readme and you can link to there.

**Comment by nicolasgarnier** [comment]
You can link to the following instructions for mobile apps: https://github.com/firebase/friendlypix-web/blob/master/README.md#mobile-apps

**Comment by igor9silva** [comment]
Thanks for the info @nicolasgarnier. I happened to have deployed them all at once, as expected.

Maybe just pointing out that deploying the whole `web` project is a requirement would do the job.

**Comment by igor9silva** [comment]
Done @nicolasgarnier. I'll update Android repo as well.

**Pull request merged**
